### PR TITLE
Make sure that v8 flags are passed properly through the `respawn` event

### PR DESCRIPTION
**Pull request by tusbar**
See https://github.com/js-cli/js-flagged-respawn/pull/1.

### CODE REVIEW

**Comment by tkellen** [comment]
**Thank you** @tusbar!

You have commit bit here and publish access on NPM now. Land and release away! If you have the bandwidth to coordinate with @sttk on https://github.com/js-cli/js-liftoff/issues/8#issuecomment-198863805 I'd deeply appreciate it :)

**Comment by phated** [comment]
@tusbar awesome work!  thanks!!!

**Comment by tusbar** [comment]
@tkellen as this is just a bugfix, I believe that #8 should be in a separate minor release.

**Comment by tkellen** [comment]
@tusbar :+1:, I wasn't suggesting we make them part of the same release, just hoping you'd have the bandwidth/interest in pursuing a resolution to #8 as it has been a longstanding request (the primary use case is exposing `.apprc` files via Liftoff so consumers can support things like default command line switches/etc

**Pull request merged**
