### PR TITLE
Remove lodash

### PR DESCRIPTION
**Pull request by sttk**
This pr is for #85.

### CODE REVIEW

**Comment by phated** [comment]
@sttk Can you remove the travis changes? I know OSX takes a long time to run but it's nice to have.

**Comment by sttk** [comment]
@phated I've removed the travis changes.

The failure of travis will be fixed by  #87.

**Comment by phated** [comment]
Ran this on a new branch and it passed.  Thanks again @sttk

**Comment by sttk** [comment]
@phated Thank you for merging this, too.

**Pull request merged**
