### PR TITLE
Add node 6

### PR DESCRIPTION
**Pull request by Vanuan**
Verify if tests pass on Node 6

### CODE REVIEW

**Comment by phated** [comment]
Can you actually update this to be:
```yml
- "0.10"
- "0.12"
- "4"
- "5"
- "stable"
```

**Comment by jonschlinkert** [comment]
I believe `stable` has been deprecated. See:

- https://nodejs.org/en/blog/release/v6.0.0/#current-what-happened-to-stable
- https://github.com/travis-ci/docs-travis-ci-com/pull/534

**Comment by phated** [comment]
Yeah, @jonschlinkert is correct.

Can this be updated to: 
```yml
- "0.10"
- "0.12"
- "4"
- "5"
- "6"
```
instead?

**Comment by phated** [comment]
This was completed by #77

**Pull request closed without merging**
